language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_install:
  - sudo apt-get install libdb-dev libdb++-dev
  - cpanm -n Devel::Cover::Report::Coveralls

script:
  - perl Makefile.PL && make &&	cover -delete && HARNESS_PERL_SWITCHES=-MDevel::Cover make test && cover

branches:
  only:
    - master